disabled_rules:
  - trailing_whitespace
  - todo
opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Pods
  - Carthage
  - .build
  - Generated

line_length: 120
file_length:
  warning: 500
  error: 1200
type_body_length:
  warning: 300
  error: 600
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
